### PR TITLE
Updated David Akim - dakim.ts

### PR DESCRIPTION
**Pull request by david-001**
## Linked Issue
#13 
#1240 

## Description
Give David Akim Hacktoberfest 2024 Badge! Update Linkedin link and dev.to link.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by BekahHW** [comment]
Hey @david-001 it looks like there's some merge conflicts there. Can you try to fix them or let us know if you need help?

**Comment by david-001** [comment]
Hi @BekahHW I think I fixed the merge conflicts. Can you check and let me know. Thanks!

**Comment by meg-gutshall** [comment]
Hey David! The build is still failing. It may be easier to delete your copy of the repo and start completely new to make sure you don't have any conflicts. If you do so, you can either close this PR and start a new one or force push the code onto it. Let us know if you have questions/need help!

**Review by danieltott — APPROVED** [review]
@david-001 I removed the extra files that got added and now we're all good!

**Pull request merged**
