### PR TITLE
Add new page for December Challenge

### LINKED ISSUE #482: December Monthly Challenge
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

Brand new page

### URL of existing page

_No response_

### Context for content change

We need to get the new monthly challenge page up on the site for our `Creative Community Challenge`.

### Proposed solution

Create a new page to support the December monthly challenge.

### Resources that can help

Here is the relevant discussion and suggested content: https://github.com/Virtual-Coffee/VC-Contributors/discussions/227

### Collaborators

Suggested Reviewers:
@tkshill 
@BekahHW 
@aurelie-verrot 
@abbeyperini 

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

### PR DESCRIPTION
**Pull request by Andrew-Bush**
## Linked Issue

Closes #482 

## Description

This adds the new page for the December Monthly challenge.

Thank you to Abbey and Kirk for creating the content.  I wrote up the page itself quite quickly and it needs a thorough review.  I think we could maybe use a few more details regarding hashtags and participation, but that can come in a subsequent PR if that is alright.

I would value input from anyone.  I want to callout these folks since they have contributed to this already.
- @tkshill 
- @abbeyperini 
- @BekahHW 
- @aurelie-verrot 

## Methodology

https://github.com/Virtual-Coffee/VC-Contributors/discussions/227 here is the initial discussion for these changes.  This was done as part of the regular release cycle for the monthly challenge team.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by danieltott** [comment]
deploy preview: https://deploy-preview-483--virtual-coffee-io.netlify.app/monthlychallenges/dec-2021/

**Review by tkshill — APPROVED** [review]
Approved but I know you noted that Header tacked onto the subheading quirk @Andrew-Bush. That's the only thing I'd adjust

**Comment by BekahHW** [comment]
A couple of things:

Let's title it: "Creative Community Challenge"
We can add the subtitle: Let's make some space for the other parts of ourselves.
(I really like that!)

LANGUAGE CHANGE: `beyond the text editor.` I like this idea, but also want to keep it open to ppl creating css art or fun stuff with code. What can we add to keep it inclusive?


Typo: `If someone is doing something your interested in` should be `...you're interested in`

**Comment by abbeyperini** [comment]
maybe "embracing self-expression" rather than "embracing the aspects of yourself beyond the text editor"?

**Pull request merged**
