### PR TITLE
virtualcoffee.io V2 (work in progress)

### PR DESCRIPTION
**Pull request by danieltott**
## VirtualCoffee 2: The Search for More Coffee

Some highlights:

- New design
- [11ty](https://www.11ty.dev)
- Asset build tasks
- Clear path for adding pages
- Foundation for adding other planned features
- Easy to use commands for local development

### CODE REVIEW

**Comment by danieltott** [comment]
Currently there's a bunch of extra stuff in here from the 11ty template and other sorts of nonsense.

**Comment by BekahHW** [comment]
The link to the COC isn't working for me.

`Cannot GET /code-of-conduct`

I tried putting the permalink in quotes, but that did nothing. Trying to figure out how this stuff works.

**Comment by danieltott** [comment]
This is in pretty good shape for a first release of the new version.

Happy to adjust anything

- I pulled the orange and pink from https://www.happyhues.co/palettes/9
- I pulled the illustrations from https://undraw.co/illustrations
- Using `grunt` for builds because everything is awful
- Used bootstrap because I'm awesome

**Comment by danieltott** [comment]
More general notes:

The font stack is set to [a native font stack](https://getbootstrap.com/docs/4.5/content/reboot/#native-font-stack) - It will look a bit different on each user's machine, but requires no downloads or anything like that. Would be happy to look into using some other fonts if we'd want

Not sure about the ☕  emoji in the title - would be fine removing that if it's too much.

**Comment by BekahHW** [comment]
This looks good to me. Maybe we can get one more set of eyes on it. @healeyb @tkshill @saramccombs? Anyone got a couple of minutes?

**Pull request merged**
