### PR TITLE
add rahat posts

### PR DESCRIPTION
**Pull request by Rahat-ch**
## Linked Issue

#91 

## Description

This PR adds blog posts I have written this month to the monthly challenge json file for November.

## Methodology

This was done to track my posts and add my blog to the number of blog posts written by us.

### CODE REVIEW

**Comment by danieltott** [comment]
Thanks @Rahat-ch !! 

Can you do me a favor and revert that package lock file change? I’m still looking in to how to prevent that from happening but for now I’m trying to keep these PRs single-change. Thank you 🙏 !

**Comment by Rahat-ch** [comment]
@danieltott no worries -it's not updating the fact that I removed it for some reason - I'll create a new PR

**Comment by Rahat-ch** [comment]
> @danieltott no worries -it's not updating the fact that I removed it for some reason - I'll create a new PR

nevermind got it!

**Comment by danieltott** [comment]
Thank you!!

**Pull request merged**
