### PR TITLE
Docs: Add March 2024 challenge to the website

### LINKED ISSUE #1131: Add March 2024 Monthly Challenge
February monthly challenge is "Month of Learning Challenge"  and we need to change the monthly challenge page of the site.

To make the updates:

1. Go to `app/routes/__frontend/monthlychallenges/index.tsx`.
   - [ ] Set `current: true` to the "Get Job Ready" challenge and remove it from "Month of Learning Challenge" challenge. 
   - [ ] Add completed challenge alert to February challenge.

 2.  Go to `app\routes\__frontend\monthlychallenges`.
     - [ ] Create `mar-2024.jsx` file.
     - [ ] Use the content of last year's Get Job Ready challenge and adjust it based on the needs of current challenge.

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

Closes #1131 

## Description

This PR adds March 2024 challenge (Get Job Ready) to the website with changes as follow:

1. In the `app/routes/__frontend/monthlychallenges/index.tsx`:
   - [x] Set `current: true` to the "Get Job Ready" challenge and remove it from "Month of Learning Challenge" challenge. 
   - [x] Add completed challenge alert to February challenge.

 2.  In the `app\routes\__frontend\monthlychallenges`:
     - [x] Create `mar-2024.jsx` file.
     - [x] Use the content of last year's Get Job Ready challenge and adjust it based on the needs of current challenge.

### Live Preview

**Monthly challenge page**

**March challenge page**

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by adiati98** [comment]
Hey @danieltott,

I didn't pass the "Header rules" check, but the error message is not really clear.
So, I'm not sure how to troubleshoot here. Can you help me out? TIA! 😄

Screenshot 2024-02-25 221649

**Comment by danieltott** [comment]
@adiati98 there were some configuration issues on netlify that I resolved - if you push up a change it should re-build successfully 👍🏼

**Comment by danieltott** [comment]
@adiati98 it's all set now - here's the deploy preview for the new page: https://deploy-preview-1133--virtual-coffee-io.netlify.app/monthlychallenges/mar-2024

**Comment by adiati98** [comment]
Thanks a lot, @danieltott! 🎉

**Review by dominicduffin1 — APPROVED** [review]

**Review by danieltott — APPROVED** [review]

**Pull request merged**
