### PR TITLE
Add to Calendar button on event cards

### LINKED ISSUE #565: Add calendar links to "Upcoming Events" page items
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

I think it would be helpful for our members to be able to add events they are interested in attending to their calendar of choice directly from the event posting. 

### Proposed solution

I believe we could use the [calendar-link](https://www.npmjs.com/package/calendar-link) library to add links to each event card.

I'd like to give this a shot if there is interest in this feature.

### Alternatives Considered

_No response_

### Additional Resources

_No response_

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

### PR DESCRIPTION
**Pull request by JoeKarow**
## Linked Issue
Closes #565 

## Description

- Added [calendar-link](https://www.npmjs.com/package/calendar-link) library to automatically generate ics string
- Added button to card header

## Methodology

QoL improvement for members to add events to their calendar directly from the event listing.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Review by danieltott — CHANGES_REQUESTED** [review]
@JoeKarow this is so awesome! Thank you for getting this rolling ❤️

I was thinking we should move the `ics` calculation into the data function inside the loader, instead of inside the component. Doing this would make it so we'd never have to load the `ics` code on the client side.

I was thinking we could add it here:

https://github.com/Virtual-Coffee/virtualcoffee.io/blob/46da98fb3d6aecc37bd180eded3149221cb4871a/app/data/events.js#L70

And call it `ics` or `icsLink` or something like that. Then in the component we could to `href={event.icsLink}`.

Let me know if this makes sense.

**Comment by JoeKarow** [comment]
@danieltott Yep, totally! I'll make those changes.

**Comment by JoeKarow** [comment]
Hey Dan,

I made the changes. I had to add the ICS generation in both of the production loader and the mock loader for testing. I don't have an API key, so I'm not 100% sure that it works for live data, but it did work with the mock.

**Review by danieltott — APPROVED** [review]
@JoeKarow this is awesome! Great work 🎉 

boom

**Comment by JoeKarow** [comment]
Woooo! I'm a functioning member of the open source society now!

**Pull request merged**
