### PR TITLE
Added August 2022 Monthly Challenge

### LINKED ISSUE #605: Add New Monthly Challenge
## Issue Context
*Add New Challenge to the Site*

You can use [June 2021](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/app/routes/monthlychallenges/june-2021.jsx) as kind of a template

## Steps
- [ ] Follow the instructions for [creating monthly challenge pages](https://github.com/Virtual-Coffee/virtualcoffee.io/#monthly-challenges)
- [ ] Create a PR that uses `closes #{number of this issue}`
- [ ] Request @BekahHW to review PR once ready.

### PR DESCRIPTION
**Pull request by klezi10**
## Linked Issue
Closes #605 

## Description
I added a new monthly challenge for August 2022.

## Methodology
- I followed the instructions for [creating monthly challenge pages](https://github.com/Virtual-Coffee/virtualcoffee.io/#monthly-challenges)
- I used the content of the [Aug 2021](https://virtualcoffee.io/monthlychallenges/aug-2021) challenge.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by klezi10** [comment]
@BekahHW I don't think I'm able to add you as a reviewer.

**Comment by BekahHW** [comment]
This looks great, @klezi10! I have one small note and it's my fault for not communicating it. Can we change the name of the challenge to "Healthy Habits for Happy Devs"? If you don't have time before August 1st, just let me know.

**Comment by klezi10** [comment]
Let me know if you need any other changes.

**Comment by BekahHW** [comment]
sponge bob thanks @klezi10

**Pull request merged**
