### PR TITLE
replace coc text link and enforcement headline

### LINKED ISSUE #703: Add CoC Violation Report Link to CoC Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

New section on existing page

### URL of existing page

https://virtualcoffee.io/code-of-conduct

### Context for content change

I can never find the [Report a Code of Conduct Violation page](https://virtualcoffee.io/report-coc-violation) when I need it... and that's **bad!**

### Proposed solution

Add a link for the [Report a Code of Conduct Violation page](https://virtualcoffee.io/report-coc-violation) to the [Virtual Coffee Code of Conduct page](https://virtualcoffee.io/code-of-conduct)! I would add both the Code of Conduct link and Code of Conduct Violation Report link to the [Member Resources page](https://virtualcoffee.io/resources) as well.

### Resources that can help

It should be easy enough to do with [GitHub-flavored markdown](https://github.github.com/gfm/).

### Collaborators

In the spirit of Hacktoberfest, I'd love to put this up-for-grabs!

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

### PR DESCRIPTION
**Pull request by carmenkolohe**
## Linked Issue
- closes #703 

## Description

Replace the text https://virtualcoffee.io/report-coc-violation with a link to that page and the text "our CoC violation form" and headline "enforcement" with "Reporting Code of Conduct Violations"

## Methodology

Improve finding link to VC's report CoC violation form for folks to find it quickly when needed.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Review by danieltott — CHANGES_REQUESTED** [review]
Hey @carmenkolohe !

These changes are good content-wise, but this is the wrong file! This file really shouldn't even be in here (my fault) - it's from the old version of the site. The current file is located at `app/routes/__frontend/__simpleMdx/code-of-conduct.mdx` - if you could make the changes there, that would be great!

**Comment by carmenkolohe** [comment]
Oh my goodness sorry about the misunderstanding! Thanks for letting me know. Will make those changes and push a new branch soon. Do you want me to make a new PR?

**Comment by danieltott** [comment]
No need to create a new branch - just use the same branch and push it up!

**Comment by carmenkolohe** [comment]
@danieltott I reverted the other file to its original text and made changes to the appropriate file.

**Review by danieltott — APPROVED** [review]
Thank you @carmenkolohe!

**Pull request merged**
