### PR TITLE
Feature/add guide for VC prospective members

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

#311 

## Description

Create and add the guide to joining VC for prospective/new members.

### CODE REVIEW

**Comment by adiati98** [comment]
@danieltott 
Sorry for the delay, but the guide for prospective members is here! 😄
It probably needs some edits (and additions?)

**Review by BekahHW — APPROVED** [review]

**Comment by adiati98** [comment]
@BekahHW thank you so much for the edit and review! 🙌

I made a quick fix on a blush emoji because it was rendered as `:blush:` instead of an emoji as per screenshot attached. 
<br>

blush-emoji-error

@danieltott it's interesting how emoji's markdown doesn't render while the syntax is right 🤔

**Comment by BekahHW** [comment]
🤦🏼‍♀️Thanks, Ayu. I will use the "it was working on my machine" excuse 🤣

**Comment by danieltott** [comment]
Thank you so much @adiati98 this is amazing!!! ❤️  

thank you

**Comment by adiati98** [comment]
Thank you so much, @danieltott & @BekahHW! ❤

**Pull request merged**
