### PR TITLE
Members/cljarvis

### PR DESCRIPTION
**Pull request by ClJarvis**
## Linked Issue
This is for #1240 add 2024 badge

## Description
profile update for 2024

## Methodology
followed the docs and livestrem

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Review by danieltott — CHANGES_REQUESTED** [review]
Hey @ClJarvis - had one change/question on this one!

**Comment by ClJarvis** [comment]
Yes I'm not active there anymore. I'll update it.

**Comment by ClJarvis** [comment]
Commented out the link. 
Thanks

**Comment by ClJarvis** [comment]
It'll be easier to just delete the old repo, the start over right?

**Comment by danieltott** [comment]
> It'll be easier to just delete the old repo, then start over right?

Yes it most likely will. Feel free to delete this PR, or you can force-push to this branch and leave this PR open if you want. Either way is cool with me!

**Pull request closed without merging**
