### PR TITLE
Add May 2022 newsletter

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

#575 

## Description

- Add May 2022 newsletter to the website.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by adiati98** [comment]
Hi @danieltott,
I want to let you know that currently, we have double `h1` and sub-header `p` for our newsletter pages (screenshot attached).
I believe one is coming from `meta` and the other one is from the `Issue` function?

Would we keep both of them?

double-h1-and-p

**Comment by danieltott** [comment]
@adiati98 yeah, there should not be the h1/p in the body at all. The one in `2022-04` is a mistake - feel free to delete it!

**Comment by adiati98** [comment]
> @adiati98 yeah, there should not be the h1/p in the body at all. The one in `2022-04` is a mistake - feel free to delete it!

@danieltott Done 👍

**Comment by adiati98** [comment]
Hi @danieltott,
I've deleted `h1` and `p` in both `2022-04` and `2022-05`.
They're ready to merge 😊

Thank you!

**Comment by danieltott** [comment]
you rock

**Pull request merged**
