### PR TITLE
Feature/add channel guide

### LINKED ISSUE #310: Add Slack channel guide to member resources
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

We now have a [Member Resources section](https://virtualcoffee.io/member-resources/) on the site. The [Slack section](https://virtualcoffee.io/member-resources/guide-to-vc/#vc-slack) has a few interesting channels which is great, but we've always wanted a Slack channel guide. 

### Proposed solution

This should be a new page that is purely the channel guide. We can link to it from other sections, and it will show up in the index. We can model this after the Slack section of the VC Guide, or come up with some new styles.

### Alternatives Considered

_No response_

### Additional Resources

Here are all the current channels!

### ideas
**Purpose:** This *channel* is for sharing ideas with your team. It's a place for inspiration, eurekas, and fresh perspectives.
**Topic:** 

### random
**Purpose:** Unlock all the achievements
**Topic:** 

### announcements
**Purpose:** This *channel* is for announcements. Everyone is automatically added, so it’s a good place for you to reach your whole team.
**Topic:** This channel is for official VC announcements.

Code of Conduct: https://virtualcoffee.io/code-of-conduct/

### general
**Purpose:** 
**Topic:** 

### welcome
**Purpose:** In Slack, conversations are organized into *channels*. Like this one, which is a place for you and your teammates to say hello.
**Topic:** 

### team
**Purpose:** This *channel* is for you and your team. It’s a place for sharing updates, planning your week, and staying connected wherever you are.
**Topic:** 

### pairing
**Purpose:** find a partner to pair up on an issue, project, or just some conversation
**Topic:** 

### heavy
**Purpose:** 
**Topic:** 

### articles-and-resources
**Purpose:** A channel to drop useful articles and resources
**Topic:** 

### book-club
**Purpose:** VC Amazon Book Club
To join:

Edit
**Topic:** July/Aug book: “Turn the Ship Around!”
This week’s reading:
Part 4 - Clarity
Aug 23-29, Chapters 25-29 (29 pgs)

### job-hunt
**Purpose:** This is the place for your job hunt and our support for good work in tech.

External job postings are not vetted by Virtual Coffee maintainers, but posts and interactions in the VC space should adhere to the COC.
**Topic:** Jobs, Resumes, Interview….et al.

### happiness
**Purpose:** Just a place to post things that make you happy
**Topic:** Goats are nice.

### goals-and-wins
**Purpose:** 
**Topic:** discuss your goals for the week and celebrate your wins

### health-and-fitness
**Purpose:** 
**Topic:** 

### past-midnight
**Purpose:** a channel for insomniacs
**Topic:** The young and the restless.

### open-source
**Purpose:** Discuss ways to create and contribute to open-source projects
**Topic:** https://github.com/Virtual-Coffee/open-source
https://github.com/Virtual-Coffee/virtual-coffee.github.io

### frontend
**Purpose:** All things frontend. From bundlers to MDN
**Topic:** 

### help-and-pairing
**Purpose:** Judgement-free help zone.
**Topic:** A space to ask for and provide help. Members who provide office hours are in the pinned spreadsheet.

### codeland-discussion
**Purpose:** 
**Topic:** https://codelandconf.com/

### vc-events
**Purpose:** Check out the pinned messages for the Lunch &amp; Learn form and any other event-related forms :slightly_smiling_face:

Some of our events have their own channels for continual discussion, so be sure to check out what other channels we have goin
**Topic:** This channel is for announcements and discussion of both official Virtual Coffee events and member-lead events for VC members.

All official VC events appear on http://meetingplace.io|meetingplace.io, but for member-only official events, we'll drop...

### parenting
**Purpose:** 
**Topic:** 

### game-night
**Purpose:** Want to game with other VC'ers? It can be anything from a fun website, Catan Online or even something on Steam.
**Topic:** Want to game with other VC'er? Post here :smile:

### music
**Purpose:** 
**Topic:** Music is good.

### food
**Purpose:** Weekly Inspiration: Favorite breakfast dishes
**Topic:** Weekly Inspiration: Favorite vegetarian dishes! 

### feed
**Purpose:** 
**Topic:** 

### neurodiverse
**Purpose:** 
**Topic:** 

### find-partner
**Purpose:** Looking for a long term partner on a technical project/idea? Looking to work with someone to help actualize their idea? This is the place to share!
**Topic:** 

### politics
**Purpose:** 
**Topic:** Code of Conduct: https://virtualcoffee.io/code-of-conduct/

### lgbtq-plus
**Purpose:** A compassionate space where people can feel comfortable expressing their gender and sexual identities, and discussing issues in the space. Here to meet and love each other as we truly are.
**Topic:** :rainbow-flag: :nerd_face: :heart:

### apple-stuff
**Purpose:** 
**Topic:** 

### humor
**Purpose:** Humor that embraces the Virtual Coffee COC, like 999%.
**Topic:** 

### hacktoberfest-contributor
**Purpose:** A channel for discussion of all things Hacktoberfest. Talk about what you're working on, questions you have, or any other ideas you have. I
**Topic:** 

### tech-interview-study-group
**Purpose:** A group made for Virtual Coffee members who may need help studying for technical interviews to come together, ask questions, maybe run study sessions and generally help each other interview and get the job!!
**Topic:** :sparkles:July’s theme: Interviews!
:calendar: Upcoming Special guests: Kevin Truong July 12
:question: Mock Interview @U01CE1F1XQ8 July 14 lead by @U01JXQGMSUC

### apple
**Purpose:** temp channel for apple event
**Topic:** 

### region-europe
**Purpose:** 
**Topic:** 

### code-challenges
**Purpose:** Let's solve a coding challenge together!
**Topic:** Are you doing Exercism ( https://exercism.io/ ), CodeWars ( https://www.codewars.com/ ) or another code challenge? Yay!!

This channel is the perfect place to flex your skills, or ask for help :tada:

### event-chat
**Purpose:** 
**Topic:** 

### lightning-talks
**Purpose:** planning, decisions, details
**Topic:** 

### monthly-challenge
**Purpose:** https://virtualcoffee.io/monthlychallenges/july-2021/

Let's use check-ins to keep each other informed on our progress.
**Topic:** Monthly Challenge August 2021: Month of Healthy Habits!

This month's challenge is all about nourishing our bodies, minds, and spirits so that we can become healthier developers.

### consulting-and-freelancing
**Purpose:** Discuss business aspects of consulting, get support on client issues
**Topic:** 

### gifts
**Purpose:** 
**Topic:** 

### tech-products
**Purpose:** List your favorite software, learning resources, equipment—all of your tech go-to’s! Also highlight deals/sales and ask for recommendations here.
**Topic:** List your favorite software, learning resources, equipment—all of your tech go-to’s! Also highlight deals/sales and ask for recommendations here.

### new-channels
**Purpose:** A place to announce new channels or discuss channel organization or new channels. 
**Topic:** 

### spanish
**Purpose:** Come here to practice your Spanish language skills!
**Topic:** Come here to practice your Spanish language skills!

### content-creation
**Purpose:** Creating content about code, your journey into code, or anything else? We’re here to support you, offer feedback, and check out what you’ve created. It can be written, audio, video, or anything else!
**Topic:** Content you're creating. Questions about creating. A space for feedback. A place to organize VC  content-creation meet-ups.

### francophones
**Purpose:** 
**Topic:** 

### nye
**Purpose:** VC’s New Year’s Eve celebration event channel
**Topic:** VC’s New Year’s Eve celebration event channel

### add-new-channel
**Purpose:** Discuss or announce new channel additions
**Topic:** 

### sportsball
**Purpose:** nerds that the cool kids mostly left alone
**Topic:** 

### external-events
**Purpose:** Announce non-VC-affiliated tech events here!
**Topic:** Announce non-VC-affiliated tech events here! When sharing a conference, include if it’s free and any scholarship opportunities if not. Please be mindful to post events that share the spirit of authenticity, community, and inclusion that VC embraces.

### i-love-plants
**Purpose:** For plant parents!
**Topic:** A place for plant parents to trade tips or those that merely respect plants to hang out and take it all in

### lightning-talk-mentors
**Purpose:** For mentors to chat through their experiences and ask each other questions. 
**Topic:** 

### accessibility
**Purpose:** Questions, comments, tips, answers about a11y for accessibility.
**Topic:** 

### machine-learning
**Purpose:** machine learning, statistics, linguistics
**Topic:** 

### wordpress
**Purpose:** A place to discuss all things WordPress
**Topic:** 

### mental-health
**Purpose:** Sharing status, approaches, intentionally listening. 
**Topic:** 

### indie-startup-hackers
**Purpose:** For indie hackers, startups, bootstrappers and side projects
**Topic:** Indie hackers, bootstrappers and founders unite! Any and all questions on creating your own gig welcome.
May your MRR necessitate the frequent posting of screenshots: @U014DKGQHA9

### co-working-room

Virtual Coffee’s Co-Working Room. Always open.

Please abide by our Code of Conduct:
https://virtualcoffee.io/code-of-conduct/
**Topic:** 

### making-stuff
**Purpose:** A place to share things you make! Hobbies, crafts, costumes, woodworking, or anything else IRL!
**Topic:** 

### overheard-quotes
**Purpose:** 
**Topic:** 

### manga-anime
**Purpose:** Nerds unite. Inclusive space to discuss your favourite manga, anime, etc. Please use the #spoiler tag when starting threads about new releases, chapters etc. As with all other spaces in the Slack, we remain respectful and kind here. No NSFW content.
**Topic:** 

### coffee
**Purpose:** the dirty bean water channel
**Topic:** beans, beans, beans, the magical fruit.

### gratitude
**Purpose:** a channel dedicated to shoutouts &amp; kind words
**Topic:** 

### cybersecurity
**Purpose:** A place to discuss all things related to cybersecurity
**Topic:** 

### big-energy
**Purpose:** Go get it
**Topic:** 

### just-javascript
**Purpose:** support, co-learning, chat about Just JavaScript
**Topic:** 

### san-diego
**Purpose:** Planning local San Diego VC meetup
**Topic:** 
react_devtools_backend.js:4049:25

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

### PR DESCRIPTION
**Pull request by danieltott**
## Linked Issue

- closes #310 

## Description

- Added a markdown file for the Slack channel guide that @adiati98 created ❤️

### CODE REVIEW

**Comment by danieltott** [comment]
@adiati98 here's the slack guide - would love a review from you if you get a moment!

**Comment by adiati98** [comment]
> @adiati98 here's the slack guide - would love a review from you if you get a moment!

This looks great, @danieltott! 🎉


shaun the sheep looks great gif

**Comment by adiati98** [comment]
@danieltott I just realized #machine-learning channel is changed into #machine-learning-and-data. I'm not sure if this would be data science or database, because I think someone asked about databases channel.

@BekahHW what is the better description for that channel now?
Originally:
> Anything about machine learning is happening in this channel.

**Review by tkshill — APPROVED** [review]
APPROVED

**Pull request merged**
