### PR TITLE
February 2022 newsletter

### LINKED ISSUE #519: Add February 2022 newsletter to site
## Issue Context

Every month, we try to get the newsletter up on the site within a week of sending it out. Currently, we're moving them over "by hand."

You can look at the existing newsletters ( src > newsletter > issues) as a kind of template. The sections are all the same. The content needs to be updated, and sometimes that changes the way things look, for example, your list may have fewer items.

## Steps to update

You can look at the existing newsletters ( src > newsletter > issues) as a kind of template. The sections are all the same. The content needs to be updated, and sometimes that changes the way things look, for example, your list may have fewer items.

In the code base, navigate to src > newsletter > issues and create a new file 2022-02.njk
Add the latest issue using the format from the past issues.
If you have questions, please let us know. We're up for pairing if anyone wants to walk through this!

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

Closes #519

## Description

Add February 2022 newsletter to the website.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by adiati98** [comment]
Hey @danieltott & @BekahHW.
I created the PR draft here because we don't have new members count yet.
Otherwise, this is ready to go.

I somehow cannot add reviewers to this draft. I hope you still can review and merge it 😅

Thank you!

**Comment by adiati98** [comment]
Hi @danieltott & @BekahHW, 
FYI, I've marked this PR as ready, so I think you're now able to review it.

Thank you 😊

**Comment by BekahHW** [comment]
Awesome! I'll check it out as soon as I'm at my computer

**Comment by BekahHW** [comment]
thank you floral

**Pull request merged**
