### PR TITLE
Nov 2021 - Karen D adding Job Hunt blog post

### PR DESCRIPTION
**Pull request by kldickenson**
## Linked Issue
#465 

## Description

Karen D adding her blog post data to the Nov. 2021 json file.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by danieltott** [comment]
Hey @kldickenson ! Sorry I didn't catch this in time, but we're using a different system for collecting blog posts now! Sign in here - https://members.virtualcoffee.io/monthly-challenges/november to add your posts! 

Let me know if you have any questions!

**Comment by adiati98** [comment]
@danieltott I opened the link, and the button to sign up is not working.
I couldn't click it.

**Comment by danieltott** [comment]
Hmm - try https://members.virtualcoffee.io/ maybe?

**Comment by adiati98** [comment]
@danieltott it does allow me to sign up from  https://members.virtualcoffee.io/ 👌

**Pull request closed without merging**
