### PR TITLE
GitHub Powerups

### PR DESCRIPTION
**Pull request by danieltott**
I have pirated issue/repo templates and contributing from @tkshill via https://github.com/tkshill/Quarto

I haven't taken a hard look at them - probably needs some refining for our specific repo/use cases

### CODE REVIEW

**Comment by tkshill** [comment]
In my contributing docs, The last 6 sections (excluding tips and gotchas) is a bit specific to my project so we should probably make that more generic or take it out for now. Everything from Awaiting Review to the end.

The templates are generic enough that it should be fine.

We may be better off plucking the [template](https://github.com/tkshill/Template/blob/main/CONTRIBUTING.md) contributing instead.

**Review by tkshill — CHANGES_REQUESTED** [review]
Probably best to remove the parts of contributing.md after Creating A Pull Request since that's all pretty specific to Quarto repo

**Comment by danieltott** [comment]
Yeah I knew it wasn't actually ready - probably should have just assigned instead of requested reviews. This was mostly just a "hey let's do this here's a start" sort of PR

**Comment by tkshill** [comment]
I can make the edits tomorrow. If anyone else has feedback they have some time to get it in.

**Pull request merged**
