### PR TITLE
feature: Add November 2023 Challenge

### LINKED ISSUE #1074: Add November Monthly Challenge page with tracker.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Context

It's almost NanoWriMo!

### Proposed solution

basically this: https://virtualcoffee.io/monthlychallenges/nov-2022.

But let's add three goals:

Goal: 100k
Stretch Goal: 125k
Extra Stretch Goal: 150k

It would be great to figure out a visual indication that we completed our goal. 

Right now, it says stretch goal, but it looks like we didn't complete the challenge. 

image

### Alternatives Considered

_No response_

### Additional Resources

_No response_

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

Closes #1074 

## Description

This PR adds November challenge onto the webpage with details as follow:

- Added `nov-2023.tsx` --> copied and updated from `app/routes/__frontend/monthlychallenges/nov-2022.tsx`.
- Updated `monthlychallenges/index.tsx` with current challenge.
- Updated `data/monthlyChallenges/getChallenges.ts`.
- Added the alert of challenge is complete in `app/routes/__frontend/monthlychallenges/oct-2023.tsx`

## Live Preview

Monthly Challenge Page:
https://deploy-preview-1077--virtual-coffee-io.netlify.app/monthlychallenges

November Challenge Page:
https://deploy-preview-1077--virtual-coffee-io.netlify.app/monthlychallenges/nov-2023

October Challenge Page:
https://deploy-preview-1077--virtual-coffee-io.netlify.app/monthlychallenges/oct-2023

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by adiati98** [comment]
@danieltott I've copied the `nov-2022.tsx` and added `nov-2022.tsx`.
I get yelled a lot by TypeScript and I also don't have an API keys, so I can't check it out locally.

I created updated as much as I know, and created this PR for you to check.
Please let me know if I need to fix anything. TIA 😄

**Comment by BekahHW** [comment]
This looks good to me. We can merge this in after @danieltott makes the form updates.

@danieltott what do you think about putting the link to the form on the page? We can specify that it's for members only and delete any entries that aren't from VC members if that happens to be an issue. I'm just trying to think of what we can do to make it easy for members to find.

**Comment by danieltott** [comment]
> Since last year, we're embracing an official topic as well as general topics. We added a [Developer Health](https://virtualcoffee.io/resources/developer-resources/developer-health) section to our site. We'd love to feature our members' blog posts on the topic.

@adiati98 @BekahHW this is the same theme and copy from last year - are we sticking with that? It's fine if so, I just wanted to confirm.

**Comment by danieltott** [comment]
I updated the code to read from airtable this year. Here's the Deploy preview with some fake data: https://deploy-preview-1077--virtual-coffee-io.netlify.app/monthlychallenges/nov-2023

The airtable form is linked in the post, here it is for previewing: https://airtable.com/app10kd5ewHiLTjxn/shrgRjUFpNjLN1V12

**Comment by danieltott** [comment]
For context, the entire "Current status" list and table will be hidden when there are no entries, and will show up as soon as someone posts something. But let's make sure to delete those dummy entries before we merge this 😂

**Comment by adiati98** [comment]
> > Since last year, we're embracing an official topic as well as general topics. We added a [Developer Health](https://virtualcoffee.io/resources/developer-resources/developer-health) section to our site. We'd love to feature our members' blog posts on the topic.
> 
> @adiati98 @BekahHW this is the same theme and copy from last year - are we sticking with that? It's fine if so, I just wanted to confirm.

Yes, I only changed the wordings in the beginning from "This year" to "Since last year" because I'm not sure if we want to use it or not. 😁

As for me, we can omit it. Because we have a bunch of great writing ideas from last year that folks can get writing inspiration from on this page, @danieltott 😊
@BekahHW, any thoughts on this?

**Comment by danieltott** [comment]
> 
> Question: Should we log in to the add entry page later on?
> 
> Maybe make a clearer wording, too, for this part?
> 

@adiati98 I'm not sure what you're looking for here...

> In the Airtable form, there's an input for ShortDescription that is required. Would the description for the post be shown somewhere? If not, maybe we only need the title?

That's a good question. We had it last year, but I don't know that we ever used it. @BekahHW what do you think?

**Comment by adiati98** [comment]
@danieltott 

Oh 😆 
What I mean is this:

Maybe make a clearer wording for this? 👇

> Once you've written and published your content, **add your entry to our VC NaNoWriMo entry form**!

**Comment by danieltott** [comment]
@adiati98 updated 👍🏼

**Comment by adiati98** [comment]
Do we need to sign in to the entry page like previous years, @danieltott ?

**Comment by danieltott** [comment]
Nope!

**Comment by BekahHW** [comment]
@danieltott I deleted those lorem ipsum fake entries in the files. Was I not supposed to do that?

**Comment by BekahHW** [comment]
@danieltott I think it's good to go

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
