### PR TITLE
Added September 2022 Monthly Challenge

### LINKED ISSUE #615: Add New Monthly Challenge
## Issue Context
*Add New Challenge to the Site*

You can use [June 2021](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/app/routes/monthlychallenges/june-2021.jsx) as kind of a template

## Steps
- [ ] Follow the instructions for [creating monthly challenge pages](https://github.com/Virtual-Coffee/virtualcoffee.io/#monthly-challenges)
- [ ] Create a PR that uses `closes #{number of this issue}`
- [ ] Request @BekahHW to review PR once ready.

### PR DESCRIPTION
**Pull request by klezi10**
## Linked Issue
Closes #615 

## Description
I added a new monthly challenge for September 2022. @BekahHW if you could review please.

## Methodology

- I followed the instructions for [creating monthly challenge pages](https://github.com/Virtual-Coffee/virtualcoffee.io/#monthly-challenges)
- I used the content of the [Sept 2021](https://virtualcoffee.io/monthlychallenges/sept-2021) challenge.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by BekahHW** [comment]
@klezi10 this is looking great. We're sorting through some ideas for updating this challenge, so I'll get back to you asap about those updates.

**Comment by BekahHW** [comment]
@klezi10 ok, we're going to switch things up for the contributors. Here's the new copy:

## Contributors
The first step in becoming a good contributor is navigating an open source repository and understanding the time and effort maintainers put into ensuring their projects are welcoming to contributors. As we move into Hacktoberfest season, we can support maintainers in their efforts to onboard new contributors. To complete this monthly challenge, find an open source repository you'd like to contribute to and evaluate it based on our [repository checklist](https://virtualcoffee.io/resources/open-source/maintainer-guide#repository-checklist). If it doesn't meet our checklist requirements, add an issue or multiple issues asking the maintainers to update the repository based on your feedback. 

## Completing the challenge
To complete this challenge, you need to post to our [Hacktoberfest 2022 discussion](https://github.com/orgs/Virtual-Coffee/discussions/624). There are two ways to complete this challenge:
1. If the repository hasn't met the checklist requirements, post the repository and a link to the issue/issues you've added to prepare the repository for Hacktoberfest under the heading `## Needs Updated`.
2. If the repository does meet the checklist requirements, post the repository in the discussion under the heading `## VC-Verified`.

**Comment by BekahHW** [comment]
@Andrew-Bush @aurelie-verrot any other suggestions?

**Comment by klezi10** [comment]
@BekahHW I don't have write access to the repo to resolve the conflict but just need to remove
image

**Comment by BekahHW** [comment]
@danieltott do you have a min to take a look at this

**Comment by danieltott** [comment]
@klezi10 @BekahHW I reverted those changes that were causing conflicts.

@klezi10 a couple notes for the future - 

When you set up the site locally, make sure you use global flag (`-g`) to install `yarn` and `netlify-cli`. The conflicts here were because they were added locally. Check out [the readme](https://github.com/Virtual-Coffee/virtualcoffee.io#3-install-dependencies) and make sure to include `-g` when installing these again.

Also, in the future, if you do end up with merge conflicts, the main way to handle them is to merge from the origin (the `main` on virtual-coffee) _into_ your forked copy. You don't need write access to the origin to solve these sorts of conflicts. GitHub [has some good docs on this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts).

Hopefully that makes some sense - feel free to reach out with any questions. And thank you!

**Comment by klezi10** [comment]
Makes sense. Thanks so much for the details @danieltott - appreciate it!

**Comment by danieltott** [comment]
Thank you @klezi10 !!
you rock

**Pull request merged**
