### PR TITLE
Guide to Open Source

### PR DESCRIPTION
**Pull request by dominicduffin1**
Deploy preview here: https://deploy-preview-420--virtual-coffee-io.netlify.app/resources/open-source

## Linked Issue

See discussion #419 

## Description

I've placed an outline for discussion in the markdown file.

### CODE REVIEW

**Comment by dominicduffin1** [comment]
I've added an update in discussion #419

**Comment by danieltott** [comment]
@dominicduffin1 I updated this branch to exist in the new Remix environment! Make sure you pull down changes before doing more work (: 

Please reach out if you run into any issues

**Comment by dominicduffin1** [comment]
> @dominicduffin1 I updated this branch to exist in the new Remix environment! Make sure you pull down changes before doing more work (:
> 
> Please reach out if you run into any issues

Thank you @danieltott

**Comment by danieltott** [comment]
@dominicduffin1 @adiati98 This is looking really great - thank you both for the work on this!!

**Comment by danieltott** [comment]
Thank you @dominicduffin1 and @adiati98 so much for this!!!

amazing

**Comment by adiati98** [comment]
Thank you, @danieltott!
And thank you so much, @dominicduffin1, for all the hard work! You're awesome! 🙌

thank you - Keanu Reeves GIF

**Pull request merged**
