### PR TITLE
add the February challenge 2022

### LINKED ISSUE #511: February Challenge: Pairing
We're moving on from Creative Community and onto Month of Pairing. 

 ## Issue Context

Add February Challenge to the Site

## Steps

- [ ] Add folder src > monthlychallenges > Feb-2022
- [ ] Add index.njk to the file
- [ ] Using [June 2021](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/src/monthlychallenges/june-2021/index.njk) as kind of a template, create Feb 2022
- [ ] Create a PR that uses `closes #{number of this isse}`
- [ ] Request me to review PR once ready.

We need to get our new challenge up on the site. You can refer to [last year's challenge](https://virtualcoffee.io/monthlychallenges/dec-2020/), although we have some updates:

1. We have #learning-together channel in slack if you're looking for a study buddy or for 1:1 help they can head to #help-and-pairing. 
2. We want to add [this info](https://github.com/Virtual-Coffee/virtualcoffee.io/discussions/493) in some form to the site either as a linked resource or within the challenge.
3. We need to set a goal for the challenge.

### PR DESCRIPTION
**Pull request by redapy**
## Linked Issue
closes #511 

## Description
I added the February Challenge: Pairing, to the VC site.

## Methodology

- I followed the steps suggested in the issue description.
- I skipped the Theme and Goal parts and deleted the "How it Works" part.
- I kept the ''Who can participate?'' part and the "What if I need help" with small changes to match the current challenge.
- I added the link to create a cohort.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by redapy** [comment]
Hi @BekahHW, what do you think about the content of this? I'm not sure about it, so If there is anything that needs to be changed let me know

**Comment by BekahHW** [comment]
@redapy here's the link for the resources: https://github.com/Virtual-Coffee/virtualcoffee.io/discussions/516

You can add it and say "If you'd like to recommend a resource for pair programming or check out the resources we've collected, you can check them out on [this discussion](https://github.com/Virtual-Coffee/virtualcoffee.io/discussions/516)"

We don't have the #office-hours channel anymore. The doc for office hours can be found at the top of the #help-and-pairing channel now.

Let's figure out where we want folks to get paired, if we're going to do a weekly slack check-in, and if we'll have a sign-up sheet. 

This is looking great so far though. Thank you for taking this on!

**Comment by redapy** [comment]
Sure I'll add it, I've just been working on it.

**Comment by BekahHW** [comment]
@redapy 
thank you flashing lights

**Pull request merged**
