### PR TITLE
adding robots txt file to stop ai bots

### LINKED ISSUE #1032: Do we need a robots.txt file to stop AI crawlers?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of Change

Brand new page

### URL of existing page

_No response_

### Context for content change

Do we need a robots.txt to stop ai crawlers from training on VC content? We have a lot of content here and are adding stuff constantly.  
We also have a list of members names and socials plus now approximate locations. Do we need to disallow OpenAI and Bard from training on what our members are writing? 

### Proposed solution

I could write a roboot file that tells the crawlers to not read our files.  

### Resources that can help

_No response_

### Collaborators

_No response_

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

### PR DESCRIPTION
**Pull request by ClJarvis**
## Linked Issue
This is for issue #1032 adding a robot txt.

- closes #1032

## Description

Created a robots txt file. looked at current list of AI bots that others are blocking.

## Methodology
The file should be in the top-level directory of a site.  Is this the correct tier for the site.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Review by danieltott — CHANGES_REQUESTED** [review]
Thanks @ClJarvis 

Can you move this in to `src/app` ([docs for robots.txt in next.js](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots))

**Comment by danieltott** [comment]
@ClJarvis for documentation purposes, can you ID these bots and let us know what they are? Or if you got this list from somewhere, maybe at least a link to that list. That would be very helpful - thank you!

**Comment by ClJarvis** [comment]
@danieltott Moved the file. 

Gathering some documentation.

**Comment by ClJarvis** [comment]
NixCraft- https://www.cyberciti.biz/web-developer/block-openai-bard-bing-ai-crawler-bots-using-robots-txt-file

Wired 's list https://www.wired.com/robots.txt

Google article https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt#create_rules

**Pull request merged**
