### PR TITLE
updated deprecated links for Nick Taylor's news letter 

### PR DESCRIPTION
**Pull request by nowji**
## Linked Issue

https://github.com/Virtual-Coffee/virtualcoffee.io/issues/1120

## Description

Changed all the links for Nick Taylor's news letter to  https://www.nickyt.co/news

## Methodology

Needed to keep product up to date and not have any dead links.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by nowji** [comment]
I don't know why the text for above isn't showing but I was working off of this issue: https://github.com/Virtual-Coffee/virtualcoffee.io/issues/1120 . I simply updated the dead links for Nick Taylor's newsletter in order to keep the product up to date.

**Comment by BekahHW** [comment]
Hey @nowji, please fill out the PR template so we can review your pull request.

**Comment by nowji** [comment]
updated

**Review by danieltott — APPROVED** [review]
Thanks @nowji !

**Pull request merged**
