### PR TITLE
generate all asset aspect ratios on build

### LINKED ISSUE #678: Auto-generate SVG aspect ratios
## Note for Hacktoberfest:

Virtual Coffee is reserving all open issues for Virtual Coffee members for the month of October. 

[Find out more about becoming a member](https://virtualcoffee.io/join)

---

### Issue Context

The [`UndrawIllustration`](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/app/components/UndrawIllustration.jsx) component is used to display our nice [unDraw illustrations](https://undraw.co/).

In order to avoid layout jumps, we've added the aspect ratios of the svgs, but they're hard-coded which is hard to keep up to date.

What I'd like to do is generate these automatically.

### Build-time steps (generally):
- Write a node script that reads the svgs, gets the width/height values, and then outputs a file (json or js/ts) in `app/_generatedData` that contains that data
- Add that script to the build steps in `package.json`
- Update `UndrawIllustration` to read from that data

Things to think about:
Any time we have generated data, we have to think about the developer experience of using the data during development. For instance, what happens if we change/add an svg? Does it automatically reload, or do I have to stop and start the server again?

### Alternatives Considered

There may also be a runtime solution to this (as opposed to build-time) but I can't imagine it would be very performant. Definitely open to discussing options though.

### Additional Resources

The [`svg-parser`](https://github.com/Rich-Harris/svg-parser) package looks like it could be useful.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

### PR DESCRIPTION
**Pull request by JoeKarow**
## Linked Issue

Closes #678 

## Description

Build script that generates aspect ratio definitions for all images in the `public/assets` directory. The script will also generate a Union Type of the SVG file names for use in the `UndrawIllustration` component.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by danieltott** [comment]
@JoeKarow still looking at this one, but added `hacktoberfest-accepted` 👍🏼

**Review by danieltott — CHANGES_REQUESTED** [review]
Hey Joe - 

Still working through this a bit and got stock on a weird eslint thing. See below...

**Comment by danieltott** [comment]
@JoeKarow are you still interested in working through this? I know it's been a while. No worries if you're not interested anymore. There have been some updates to the site and the dependencies that might have resolved some of the issues we were having, it's possible catching this branch up will fix that eslint issue. Let me know one way or the other, no worries if you'd like to pass it off.

**Comment by JoeKarow** [comment]
@danieltott I've been SWAMPED with work - if someone else could take this over, I'd be appreciative!

**Comment by BekahHW** [comment]
@danieltott is this still something that needs worked on?

**Pull request closed without merging**
