### PR TITLE
Update description

### PR DESCRIPTION
**Pull request by BekahHW**
Updated the description on the front page.  I'm not tied to the content or the style, but wanted something a little more than what we had.

I did add the word intimate to the mission.

For quick reference here it is:

 

>  <p>Virtual Coffee is a laid-back conversation with developers twice a week. It's the conversation that keeps going in slack. It's the online events that support developers at all stages of the journey. It's the place where you go to make friends who all just happen to be in tech.</p>
> 
>   <p>Anyone can join! Whether you're just thinking about getting into tech or have been in it for decades.</p>
> 
>   <p>We know that growth comes at all levels and that no matter what stage of the journey you're on, you can teach and learn.</p>
> 
>   <p>So come with a question or a topic to discuss, ask for feedback on your portfolio, answer another developer's question, or just sit back and listen to others talk about tech. </p>
> 
>   <p>Our mission is to form community, allow room for growth and mentorship, and to provide a safe and intimate community for anyone interested in or in tech.</p>

### CODE REVIEW

**Review by tkshill — APPROVED** [review]
Looks good to me!

**Comment by danieltott** [comment]
I love these changes and the messaging. 

Small quibble:

> for anyone interested in or in tech.

Can this be worded a bit better? Could it be "for anyone interested in tech." - would that be inclusive of people already in tech and people learning about it?

If this was in the middle of the body I don't think I would even notice it or bring it up, but since it's the concluding sentence I was thinking it could use a `B-E-K-A-H` style strong ending 😄

**Comment by BekahHW** [comment]
Lol. Yeah that was the point I gave up.

**Comment by saramccombs** [comment]
Ok.. Like what @danieltott said above.. I think we can condense that sentence a bit since we are explicit above. 

But, the word intimate hit me a little different than how we intended... thinking of a good synonym before signing off on this one. Have a meeting for an hour starting at 3:30pm... should have a better idea then.

**Comment by BekahHW** [comment]
Better?

 <p>Our mission is to form community, allow room for growth and mentorship at all levels, and provide a safe space for everyone interested in tech.</p>

And to be clear, I don't see this as a final version of this, just as a placeholder until we talk about mission/vision/values at some point later.

**Review by saramccombs — APPROVED** [review]
I'm good with all this. Would love to have a better way to ensure the intimacy stays for front.. but you might be right that that happens through other conversations.. and maybe its highlighted elsewhere.. who knows.. but, this just feels better than what we had.

**Pull request merged**
