### PR TITLE
Convert `cmsimage.js` to Typescript

### LINKED ISSUE #689: Convert `cmsimage.js` to TypeScript
## Note for Hacktoberfest:

Virtual Coffee is reserving all open issues for Virtual Coffee members for the month of October. 

[Find out more about becoming a member](https://virtualcoffee.io/join)

---

### File

[`app/util/cmsimage.js`](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/app/util/cmsimage.js)

### Issue Context

- Might need types for `@imgix/js-core`

### Blockers
- _None_

### PR DESCRIPTION
**Pull request by JoeKarow**
## Linked Issue
Closes #689 

## Description

- Converted file to TypeScript.
- Created type for input Props.
- Imgix's `params` are [quite numerous](https://docs.imgix.com/apis/rendering), so the additional passed params are typed as `Record<string, any>`

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Review by danieltott — CHANGES_REQUESTED** [review]
@JoeKarow this is great!

Can you add some comments to the param types explaining what they are? I've meant to make sure we do this more - comments are nice esp in IDE-land. Comments can include markup as well (with links!)

Example from a project I'm working on:

```typescript
export interface StackedListProps extends BasicComponent {
  /**
   * [Classnames argument](https://github.com/JedWatson/classnames) to add/override list item styles
   */
  itemClassNames?: ClassnamesArgument;
}
```


Also re: the `settings` param, [looks like they're working on that](https://github.com/imgix/js-core/issues/308) so we may be able to improve that in the future! This works perfectly for now 👍🏼

**Comment by JoeKarow** [comment]
All set! I'm trying to get in to the habit of using JSDoc myself, too... I found this [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=mintlify.document) that should hopefully make things easier.

**Comment by JoeKarow** [comment]
I don't think it's necessary to add them in both places - I was experimenting with something. I was trying to get the documentation to show up in the VSCode intellisense when using autocomplete in the param object.. which never happened 😒

**Comment by danieltott** [comment]
I think if we go with inline comments, vscode handles them well. As a test:

```ts
type CreateCmsImageProps = {
  /**
   * Path to the image
   */
  path: string;
  /**
   * Folder for image
   */
  folder: string;
  /**
   * See https://docs.imgix.com/apis/rendering for options
   */
  settings: Record<string, any>;
};
```

results in this:
image

**Comment by JoeKarow** [comment]
Ohhhhhhhhhhhhh!

**Review by danieltott — APPROVED** [review]
YES! I love this - thank you for bearing with me

you rock

**Pull request merged**
