### PR TITLE
Add a guide to ask questions to the website

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

#417 

## Description

- Add a guide to asking questions for our members.
- Add svgs for the guide.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by adiati98** [comment]
Hi @danieltott & @BekahHW,

Sorry for taking me a while!
Would you mind reviewing this PR and letting me know if I need to fix anything?
Thank you! 😄

**Comment by adiati98** [comment]
Also, @danieltott,

I have a couple of questions:
- I included a link to the Slack channel guide. I saw and followed an example in our `join-virtual-coffee.md` --> `[Coffees (Zoom Meetings)](</member-resources/guide-to-vc/#coffees-(zoom-meetings)>)`.

  It gives me a `cannot GET <path>` error just like the link above, but that Coffees link works on the website. So, this Slack channel guide link might work as well?
- I want to give examples for the single and triple backticks, but the preview format somehow gets weird.

  This is what I tried:
  ```
    ```
    <ul>
       <li>Item 1</li>
       <li>Item 2</li>
    </ul>
    ```
  ```

  Screenshot for above example:
  
markdown-sample

  I couldn't find any resource yet on how to write a markdown code example within markdown.
  I tried the HTML `<code>` tag, but it doesn't do the trick either. Thus, for now, I don't give any examples within the guide.

Thank you in advance! 😄

**Comment by danieltott** [comment]
@adiati98 the `/member-resources` links are old, that's why they're not working. The path to the slack channel guide is `/resources/virtual-coffee/slack-channel-guide/`. I updated the link in your post 😄 


As far as displaying code bocks inside code blocks - [this guide](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) has the key:

> To display triple backticks in a fenced code block, wrap them inside quadruple backticks.

So use ```` to show code blocks that have code blocks 😅 

`````
````
```
hello!
```
````
`````

**Comment by adiati98** [comment]
@danieltott Thanks, Dan!
Let me add the examples 😄

**Comment by adiati98** [comment]
> OK so I have a conceptual question. There's a lot of good Virtual Coffee specific stuff in here. Should this be in the VC section, instead of a general Dev section? It'd be weird to land on this as a non-VC member and see all the slack channels and stuff. @BekahHW thoughts?

@danieltott I have some thoughts about this if I may jump in.

- The existing resource on our website is called `Member Resources — A collection of resources for Virtual Coffee members`.
  Based on the title, do we want this resource to be specifically for our members? 
  If we want to have resources both for the public and members, maybe we want to have 2 separate resources?
- The resources fully suitable for the public at the moment are `Open Source` and `Join Virtual Coffee`. 
  `Guide To Virtual Coffee` section also contains a little bit of Slack guide. We can move this part to a new page specific to Slack if necessary or put everything together in `VC Slack Channel Guide`.
- If we want to have separate resources, the `Guide to asking questions` can be split into two. 
  The `How To Ask Questions` section is for the public one, and the rest we can put in the member resources and name it something like `How To Utilize Slack And Where To Ask Question In Virtual Coffee` or again, in the same place as `VC Slack Channel Guide`.

However, if we put everything about Slack in one guide, my concern is that this page will be too long. But if this is not a big deal, it can be an option.

**Comment by adiati98** [comment]
> @adiati98 I think let's just move this page as-is into the VC Member resources section and remove the developer resources section. This page is pretty specific to VC and it has a lot of great stuff!

@danieltott noted!
Let me move it 😊

**Comment by adiati98** [comment]
@danieltott For clarification, I will:

- Remove the Dev section and the `index.md`.
- Move the `coding-questions-guide.md` to the member resources
- Delete the newly added SVGs.

Are these correct?

**Comment by danieltott** [comment]
@adiati98 Keep the SVG you're using in the new guide! But otherwise, yes 👍

**Comment by adiati98** [comment]
I've pushed it for the review!
Thanks, @danieltott! 😄

**Comment by danieltott** [comment]
This looks great @adiati98 
amazing

**Comment by adiati98** [comment]
Thank you, @danieltott!!! 😄💙

**Pull request merged**
