### PR TITLE
feat: Add November 2024 Challenge to the Website

### LINKED ISSUE #1285: Add November 2024 Challenge to the Website
The November monthly challenge is "Blogging Challenge" and we need to change the monthly challenge page of the site.

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

Closes #1285 

## Description

This PR adds November 2024 challenge (Blogging Challenge) to the website.

### Live Preview

**Challenge Homepage**

https://deploy-preview-1286--virtual-coffee-io.netlify.app/monthlychallenges

**Challenge Page**

https://deploy-preview-1286--virtual-coffee-io.netlify.app/monthlychallenges/nov-2024

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by adiati98** [comment]
@danieltott, FYI. The mock data for the form still appears on the page.

**Review by meg-gutshall — CHANGES_REQUESTED** [review]
**question:** Is there a reason you don't have hyperlinks set to open in a new tab? The only ones that do so are the hyperlink and button to the submission form.

I always set external links to open in a new tab so we don't navigate the user away from our site. It's a way of increasing retention and length of site visit.

If you don't have a specific reason for the way you set the hyperlinks, could you add `target="_blank" rel="noreferrer"` to the rest of the external links on the page? Besides that, it looks good to go!

**Comment by meg-gutshall** [comment]
> @danieltott, FYI. The mock data for the form still appears on the page.

@danieltott I created a **NaNoWriMo 2024** view in the **Monthly Challenges** Airtable DB. It's just waiting for you to hook it up in the codes -- I still don't know how to do that part.

**Comment by adiati98** [comment]
> **question:** Is there a reason you don't have hyperlinks set to open in a new tab? The only ones that do so are the hyperlink and button to the submission form.
> 
> I always set external links to open in a new tab so we don't navigate the user away from our site. It's a way of increasing retention and length of site visit.
> 
> If you don't have a specific reason for the way you set the hyperlinks, could you add `target="_blank" rel="noreferrer"` to the rest of the external links on the page? Besides that, it looks good to go!

Since I learned, accessibility-wise, that we [better refrain from opening new windows and tabs from a link if not necessary according to WCAG 2.0](https://www.w3.org/TR/WCAG20-TECHS/G200.html), I hold myself to add the `target="_blank" rel="noreferrer"`.

But if you think we better add it here, let's add it. 👍🏼

**Comment by meg-gutshall** [comment]
> > **question:** Is there a reason you don't have hyperlinks set to open in a new tab? The only ones that do so are the hyperlink and button to the submission form.
> > I always set external links to open in a new tab so we don't navigate the user away from our site. It's a way of increasing retention and length of site visit.
> > If you don't have a specific reason for the way you set the hyperlinks, could you add `target="_blank" rel="noreferrer"` to the rest of the external links on the page? Besides that, it looks good to go!
> 
> Since I learned, accessibility-wise, that we [better refrain from opening new windows and tabs from a link if not necessary according to WCAG 2.0](https://www.w3.org/TR/WCAG20-TECHS/G200.html), I hold myself to add the `target="_blank" rel="noreferrer"`.
> 
> But if you think we better add it here, let's add it. 👍🏼

Hmm... that's a good point though. My reasoning is from a marketing/SEO perspective, however, we do want to adhere to good A11y practices. I think your reasoning is good enough to leave it as it is, but now I'm curious...

I'm going to post in Slack and possibly on Twitter to get some feedback. Let's see what kind of responses we get back and perhaps we can come to a conclusion from there that will guide us going forward. Does that sound good to you?

**Comment by adiati98** [comment]
@meg-gutshall sounds good to me. 👍

**Comment by danieltott** [comment]
I agree with @adiati98 (and the WCAG) that opening new windows just to get users to stay longer is an anti-pattern. If a user wants to come back they know how 👍

**Review by danieltott — APPROVED** [review]

**Pull request merged**
