### PR TITLE
feat: Add October 2024 Challenge to the Website

### LINKED ISSUE #1228: Add October 2024 Challenge to the Website
The October monthly challenge is "Hacktoberfest" and we need to change the monthly challenge page of the site.

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

Closes #1228 

## Description

This PR adds September 2024 challenge (Hacktoberfest) to the website.

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by adiati98** [comment]
@danieltott about running in the local machine issue, I've deleted the `node_modules` and ran `pnpm install` again. But after running `pnpm dev`, it still closing down by itself, and I still get the same error as yesterday.

Some info:

- React version that have been installed:
    ```bash
    + react 18.3.0-canary-fdc8c81e0-20230707
    + react-dom 18.3.0-canary-fdc8c81e0-20230707
   ```
- The error persistence is: `Error: Next.js requires react >= 19.0.0 to be installed.`

**Comment by adiati98** [comment]
Also, some checks are not successful here because of building error. Because I can't run it locally, I can't troubleshoot it.

**Comment by danieltott** [comment]
@adiati98 The build failed because of a bad configuration on the hosting end. I've got that updated with a successful deploy preview: https://deploy-preview-1230--virtual-coffee-io.netlify.app/monthlychallenges/oct-2024

I also have a PR in progress to fix your local issues - hopefully #1233 will take care of that. I'll let you know!

**Review by danieltott — APPROVED** [review]

**Pull request merged**
