### PR TITLE
added danieljanderson

### PR DESCRIPTION
**Pull request by danieljanderson**
## Linked Issue

#13

### CODE REVIEW

**Comment by meg-gutshall** [comment]
We renamed the `.env.example` file to `.env` in order to preview the changes online before creating a PR which is why `.env.example` is deleted here.

**Comment by danieljanderson** [comment]
Be warned that I had to rename the .env.example to be able to see the local build.  As a result, **deleted** the **.env.example** from my repository.

**Comment by danieltott** [comment]
@danieljanderson thanks for the PR! If you could revert the commit that deletes the example env file, that would be great 👍

**Comment by danieljanderson** [comment]
@danieltott  readded the .env.example.  I also added instructions for other people not to rename that file

**Comment by danieltott** [comment]
Thank you @danieljanderson !!

**Pull request merged**
