### PR TITLE
Add leadership team section with founders and community engagement sections to the members page

### PR DESCRIPTION
**Pull request by dominicduffin1**
## Linked Issue

#64 

## Description

Leadership Team heading with two sections under it added to the `members.njk` file, replacing the one section under the Our Founders heading.

The new `<h3>` headers styled same as existing `<h2>` for now.

`communityEngagement.js` file created as an edited copy of `founders.js`

`communityEngagement` folder created in `_data`. JSON files for Bryan, Dan and Kirk moved to the new folder.

## Methodology

The styling of the `<h3>`s is as that of the `<h2>`s just to get a working demo ready for preview. We can discuss how they should be styled for production and also how the margins should work.

### CODE REVIEW

**Comment by saramccombs** [comment]
Preview looks nice but the links for my name as well as Kirk's name is missing.. curious the reason for that since they should be linking to our GitHub accounts.

**Comment by danieltott** [comment]
@dominicduffin1 this is a great start! 

Now that we can see it on the page (https://deploy-preview-68--virtual-coffee-io.netlify.app/members/) I have some ideas:

Let's make the h3s much smaller and tighten up the spacing, in order to make the "leadership" section a little more like one continuous section:

image

First thing I'd do is maybe just remove the `display-*` classes from the h3s and then you can adjust the `mb-*` values.

**Comment by danieltott** [comment]
@saramccombs so the names link to the users' website or nothing at the moment - this is true on the live site as well. I could see the value in changing this to "link to user's website, or github if no website" - that'd ideally be a new issue/PR

**Comment by dominicduffin1** [comment]
@danieltott I've removed the `display-*` from the `<h3>`s and tweaked the margins. What do you think?

**Comment by danieltott** [comment]
Nailed it! Merging now 😎

**Pull request merged**
