### PR TITLE
Add December 2022 newsletter to the website

### LINKED ISSUE #775: Add December 2022 newsletter to the website
## Issue Context

Every month, we try to get the newsletter up on the site within a week of emailing it. Currently, we're moving them over "by hand."

## Steps to update

In the code base, navigate to `app > routes > newsletter > issues` and create a new file `2022-12.jsx`.
You can look at the existing newsletters ( `app > routes > newsletter > issues`) as a template.

Make sure to add it to the index by following the steps in [Newsletters section in our README](https://github.com/Virtual-Coffee/virtualcoffee.io#newsletters) and update the content accordingly based on our email newsletter.

If you have questions, please let us know. We're up for pairing if anyone wants to walk through this!

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

Closes #775 

## Description

- Add November 2022 newsletter.
- Update ` newsletters.ts`. 

## Code of Conduct

> By submitting this pull request, you agree to follow our [Code of Conduct](https://virtualcoffee.io/code-of-conduct/)

### CODE REVIEW

**Comment by adiati98** [comment]
@danieltott I somehow can't preview the link to November monthly challenge. I get the `Unexpected server error` message, or something with API.

But I hope it works!

**Comment by danieltott** [comment]
@adiati98 here's the deploy preview: https://deploy-preview-776--virtual-coffee-io.netlify.app/newsletter/issues/2022-12

**Comment by adiati98** [comment]
@danieltott If you click on the NaNoWriMo link, it will show this error as per pic.

And I'm not sure why is that, because the link for december monthly challenge works 🤨!

[Server error message](https://user-images.githubusercontent.com/45172775/207884656-d4243b35-6728-40db-9aa1-4a73c9ffd95b.jpg)

**Comment by danieltott** [comment]
Ahh yeah that makes sense - I don't think I made a fallback for the monthly challenge. The newsletter page is looking good though

**Pull request merged**
