### PR TITLE
Member resources/guideto vc

### LINKED ISSUE #293: Create Documentation for "A Guide to Getting the Most out of VC"
## A Guide to Getting the Most out of VC

Virtual Coffee is more than our Zoom meetings. Much of the community occurs on slack and our monthly challenges.

We should create a central guide to store information on how to get the most of the Virtual Coffee (VC) community. This would help onboard new members and alert them to the benefits of joining VC. It could also inform current members of things of which they be unaware.

## Proposed solution

Build an guide to VC on the virtual Coffee site.

Have users submit content to this Issue. What helped you on VC? Is a particular Slack Channel of benefit to you? Link to a particular VC video.

This information will be collected and displayed on the Virtual Coffee.io website. 

## Outline of information 

What does Virtual Coffee Offer?

- In the zoom
- In the slack
    - How to participate in channel discussions
    - How to find relevant channels
    - Channel curation
- How to do events
    - What are the monthly challenges
    - What are Lunch and Learns
    - What else is going on
- How to volunteer
- How to contribute
- How do I keep up
   - The podcast
   - The newsletter
- Where do I go for help
    - The forms
    - The maintainers
- F.A.Q.

## Collaborators  and How to contribute

Comment on this issue thread with any suggestions.

**Open to all members**. Especially newer members that are leaning about the community. What helped you understand the Virtual Coffee Community? 

Ideal proposed by @BekahHW and @mrsantons

### PR DESCRIPTION
**Pull request by ClJarvis**
## Description

- closes #293

## Methodology

Made the index page for member resources and the start of the VC guide.

## Question
What should the order be on the Member Resources?

### CODE REVIEW

**Comment by ClJarvis** [comment]
Not ready to merge to Main. Just sending to show progress. Plus ask for feedback.

Us there a way to modify SVG sizes? I pulled a placeholder image from undraw but it tales up more space on the member-resource index page and the overall main page. If I switch to a svg already onsite it looks fine.

what order should it be 
  type: large
  key: Member Resources
  order: 6 ?

**Comment by danieltott** [comment]
@ClJarvis you have some great stuff in here to start! 

I was thinking - can we come up with a minimum amount of content to start with and get it live? then we can add/update in smaller batches. I don't want the scope of this one PR to grow too large, and if we chunk it out we can more easily have people help on specific bits.

What do you think?

**Comment by ClJarvis** [comment]
I agree. I would something and then add to it as needed.

**Comment by ClJarvis** [comment]
I think this is ready to review. 
questions I do have:  What do we use for the SVG file. I reused one from the site. When I attempted to use one from undraw it, appeared to have extra padding above the image.  I tried one named folder or filing system.

**Comment by danieltott** [comment]
@ClJarvis @adiati98 I've updated this PR with some of the content from @adiati98 

@ClJarvis take a look and see if you have any updates/changes. Thank you so much for doing all this!!

**Comment by danieltott** [comment]
I've left off the "how to become a member" part - I think this should be an entirely new page that we can add after this first page is live.

**Review by tkshill — APPROVED** [review]
Looks great @ClJarvis! Happy to get it live.

**Comment by ClJarvis** [comment]
This looks good. Excited to see it added and glad to have helped VC.

**Comment by adiati98** [comment]
> This looks good. Excited to see it added and glad to have helped VC.

Thanks a lot for the feedback and the collab, @ClJarvis! 😄

**Comment by adiati98** [comment]
> Deploy preview to page: https://deploy-preview-298--virtual-coffee-io.netlify.app/member-resources/guide-to-vc/

One quick thing, the Lunch & Learn Idea form link says "Content not found".
Is it because it's still in preview mode, @danieltott?

**Comment by ClJarvis** [comment]
Do we want the link for talk submission form on the public site? 

The link works from the pinned post in slack. But like @adiati98 sais it doesn't work on  preview. I even tried adding  "lunch-and-learn-idea / " to the preview URL and it's not found.

**Comment by ClJarvis** [comment]
I think I found it. The link for the brown bag idea needs to be fixed. On the deploy version I can get to https://deploy-preview-298--virtual-coffee-io.netlify.app/brownbag-idea/  so that part is still active. There needs to be an update to force brownbag to change to lunch and learn.

**Comment by danieltott** [comment]
@ClJarvis @adiati98 this is just this fork being behind `main` - I'll do an update real quick.

**Comment by danieltott** [comment]
@ClJarvis I think it's fine the link being here - nothing automatically happens when someone submits it, it just gets sent to maintainers. If it becomes a problem in the future we can revisit, but for now it seems fine to me!

**Review by BekahHW — APPROVED** [review]
@ClJarvis This is amazing! Thank you so much for putting this together.

**Comment by danieltott** [comment]
I love it!!

**Comment by ClJarvis** [comment]
@BekahHW Thanks. Glad I could help. @adiati98 wrote the Slack descriptions and some of the other content.

**Comment by adiati98** [comment]
Thank you all! 
@ClJarvis @danieltott @BekahHW @tkshill! 😄

**Pull request merged**
