### PR TITLE
Adds Tori's post to November monthly challenge

### PR DESCRIPTION
**Pull request by torianne02**
## Description

- adds Tori's "What is CI/CD?" article to the November monthly challenge tally

## Methodology

- I added myself to the HTML and updated the table manually.
- Running totals were also updated manually. 

## Preview
https://deploy-preview-83--virtual-coffee-io.netlify.app/monthlychallenges/nov-2020/

### CODE REVIEW

**Review by danieltott — CHANGES_REQUESTED** [review]
@torianne02 Thank you! One small change - I know this is a pain since it's hand-edited, but I was trying to sort the table by total words so it could act as a sort of leaderboard - want to scoot your `<tr>` up to be right below Vic's?

**Comment by torianne02** [comment]
> @torianne02 Thank you! One small change - I know this is a pain since it's hand-edited, but I was trying to sort the table by total words so it could act as a sort of leaderboard - want to scoot your `<tr>` up to be right below Vic's?

Yes, of course! I was wondering what the order system was and couldn't figure it out 😅

**Review by danieltott — APPROVED** [review]
💯

**Comment by danieltott** [comment]
booya!

**Pull request merged**
